Method references supported in transform and fromExpression
Mr-Mappie/mappie pull request #133
Opened 2024-11-21 15:15 UTC by AbelPelser

2024-11-21 16:05 UTC, stefankoppier commented
Sonar is a false positive (secrets cannot be used in forked PR's...) I'm gonna disable SonarQube

2024-11-21 16:07 UTC, stefankoppier commented
Can you also add this change to the changelog in `website/src/changelog.md` with the date set to `tbd`

2024-11-21 19:44 UTC, AbelPelser commented
> Can you also add this change to the changelog in `website/src/changelog.md` with the date set to `tbd` and version `0.10.0`?

Yes, done

2024-11-21 19:48 UTC, stefankoppier commented
> > Can you also add this change to the changelog in `website/src/changelog.md` with the date set to `tbd` and version `0.10.0`?
> 
> Yes, done

Sorry, I just did the same 😓 I also removed Sonar in branches, so the next build after a merge with main should succeed.

2024-11-21 20:34 UTC, AbelPelser commented
Fixed the conflicts :smile:

2024-11-21 20:52 UTC, stefankoppier requested changes

2024-11-21 20:52 UTC, stefankoppier commented on compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/ExplicitClassMappingCollector.kt
> +                            else -> throw MappiePanicException("Unexpected expression type: ${expression.type}")
I think expression.type.toString() will just return the object reference of the type object. I would suggest expression.dumpKotlinLike()

2024-11-21 20:52 UTC, stefankoppier commented on compiler-plugin/src/main/kotlin/tech/mappie/resolving/classes/ExplicitClassMappingCollector.kt
> +            target to ExpressionMappingSource(expression.valueArguments.first() as IrExpression)
Is this cast still necessary?

2024-11-21 20:52 UTC, stefankoppier commented on compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/MethodReferenceTest.kt
> +    fun `map property fromExpression should succeed with method reference`() {
I prefer this test in FromExpressionTest

2024-11-21 20:52 UTC, stefankoppier commented on compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/MethodReferenceTest.kt
> +    fun `map property fromProperty should succeed with method reference transform`() {
Maybe move this test to ObjectWithDifferentValuesTest

2024-11-21 20:52 UTC, stefankoppier commented on compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/MethodReferenceTest.kt
> +class MethodReferenceTest {
I would also like both tests with an incorrect type resulting in an error message. (Testing the code `constructor(functionExpression: IrFunctionExpression) : this(functionExpression, functionExpression.function.returnType)`

2024-11-21 23:12 UTC, AbelPelser commented on compiler-plugin/src/test/kotlin/tech/mappie/testing/objects/MethodReferenceTest.kt
> +class MethodReferenceTest {
Done, same goes for the other comments now I think

2024-11-22 08:07 UTC, stefankoppier commented
LGTM. Thanks for the PR!

2024-11-22 08:07 UTC, merged